title: Smart Compost Management System

# author:
#   name: NuwanJ
#   email: nuwanjaliyagoda@gmail.com

# Team names, titles and social links
people:
- name: N.S. Dharmarathne
  pic: default
  # pic: e18077
  position: Team Member
  social:
    - title: github
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: G.D.R. Mihiranga
  pic: default
  # pic: e18224
  position: Team Member
  social:
    - title: github
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: D.H. Mudalige
  pic: default
  # pic: e18227
  position: Team Member
  social:
    - title: github
      url: #
    - title: linkedin
      url: #
    - title: stack-overflow
      url: #

# Team names, titles and social links
supervisors:
- name: Dr. Isuru Nawinne
  pic: "isuru-nawinne.png"
  position: Senior Lecturer
  social:
    - title: email
      url: "isurunawinne@eng.pdn.ac.lk"

- name: Dr. Mahanama Wickramasinghe
  pic: "mahanama-wickramasinghe.jpg"
  position: Senior Lecturer
  social:
    - title: email
      url: "mahanamaw@eng.pdn.ac.lk"

# # Social networks (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll


university_url: "https://eng.pdn.ac.lk/"
department_url: "http://www.ce.pdn.ac.lk/"
other_references: "https://faq.ce.pdn.ac.lk/"
github_organization: "cepdnaclk"
repository: "e18-3yp-Smart-Compost-Management-System" 

# description: > # this means to ignore newlines until "show_excerpts:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Google Analytics Tracking (optional)
ga_tracking:
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
    "graphic_templates",
    "*.py",
    "*.sh",
    "*.yml"
  ]


kramdown:
  syntax_highlighter_opts:
    block:
    line_numbers: false

# Guideline:https://www.digitalocean.com/community/tutorials/jekyll-compress-html0
compress_html:
  clippings: all
  comments: all
  endings: []
  startings: []
  blanklines: true
  profile: false
  # ignore:
  #   envs: all
